- name: Create backend directory
  file: path=/opt/{{ project_name }}/{{ project_name }}/{{ project_name }} state=directory

- name: gunicorn file
  template: src=gunicorn.sh.j2 dest=/opt/{{ project_name }}-gunicorn.sh mode="u+x"

- name: local settings file
  template: src=local_settings.py.j2 dest=/opt/{{ project_name }}/{{ project_name }}/{{ project_name }}/local_settings.py
  notify: restart {{ project_name }}

- name: password for nginx
  htpasswd: path=/etc/nginx/webapp_htpasswd name=admin password={{ nginx_password }} owner=root group=www-data mode=0640

- file: path=/etc/nginx/includes state=directory
- name: Nginx proxy includes
  template: src=proxy.conf.j2 dest=/etc/nginx/includes/{{ project_name }}_proxy.conf
  notify: restart nginx
- name: Nginx static cache include
  template: src=staticcache.conf.j2 dest=/etc/nginx/includes/staticcache.conf

- name: Nginx base config
  template: src=nginx_base.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Nginx config for app
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ project_name }}.conf
  notify: restart nginx

- name: Supervisor config for backend app
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{ project_name }}.conf
  notify: restart supervisor
