- name: install libraries
  apt: name={ { item } } state=present update_cache=yes
  with_items:
    - python3-dev
    - python3-pip
    - python-pip
    - libpq-dev
    - supervisor
    - python-passlib
    - libjpeg-dev
    - zlib1g-dev

- name: upgrade pip3
  pip: name=pip executable=pip3 state=latest

- name: upgrade pip
  pip: name=pip state=latest

- name: install virtualenv
  pip: name=virtualenv executable=pip3

- include: docker.yml

- include: nginx.yml
